### ISSUE TITLE
How i can use it?

### ISSUE THREAD

**Issue by NayzZaK** [noobiewoobie/UnDawn#1]
How i can use it?

**Comment by noobiewoobie** [comment]
These are sdk dump files for the game. Assuming you know how to work with esp , you can update it to latest version using the dump file from latest version here.

**Comment by NayzZaK** [comment]
Can you help me to get one ESP ?

**Comment by noobiewoobie** [comment]
Assuming you came here from my uc post. So you can get it from uc only. If you want offsets you can use my sdk from here or use this app [https://t.me/SSpawner](url)
